# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinfo',
            name='pn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comicinfo',
            name='utter',
            field=models.CharField(max_length=1000),
        ),
    ]
