# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_auto_20161021_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_id', models.IntegerField()),
                ('mood_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_id', models.IntegerField()),
                ('comic_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='doing',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='doing',
            name='path_name',
        ),
        migrations.AddField(
            model_name='doing',
            name='bubble_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doing',
            name='comic_name',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comicinfo',
            name='comic_name',
            field=models.IntegerField(),
        ),
    ]
