# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0007_auto_20161021_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicinfo',
            old_name='utter',
            new_name='utter1',
        ),
        migrations.AddField(
            model_name='comicinfo',
            name='utter2',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comicinfo',
            name='x1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comicinfo',
            name='x2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comicinfo',
            name='y1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comicinfo',
            name='y2',
            field=models.FloatField(default=0),
        ),
    ]
